### ISSUE TITLE
一个北京小测试的仲裁经历

### ISSUE THREAD

**Issue by ztc325** [CPdogson/996.law#15]
16年毕业的功能测试工程师周某，无意间看到了这个项目，使用github也不多，所以本着帮助大家的情况，提供自己在18年仲裁胜诉的例子。

我在18年8月1日，入职了一家北京的做医疗软件的公司，职位是测试工程师，合同写的是每个月十日发工资，但是知道9月25日，我都没有领到8月份的工资，中间还经常无偿加班
并且感觉人事会一直敷衍下去，所以收集了如下证据：

1.劳动合同和打卡记录，加班时间等证明我入职工作的证据
2.打印了与人事和直属领导关于拖欠工资的谈话记录
3.与人事的谈话录音（虽然仲裁部门说不需要，只要把文字打印出来就行）
4.工资卡工资记录

值得一提的是，我在9月26日，当天通过邮政寄给我公司一份解除劳动合同通知书（很重要，不能是主动辞职申请书），并且当面提交给了人事一份通知书，当时人事就应该慌了，知道我是了解法律，并且有决心去仲裁的，所以亡羊补牢，打算提前支给我工资让我和平解约。我决心给他们拖欠工资的公司一个教训，所以在9月27日，直接去了海淀区仲裁庭，提起了仲裁申请。流程大概是先填证据表，再有一段时间准备证据，我选择了不接受和解（实际上可以先提前和公司谈谈）。

直到11月3日，正式开庭，大概去了仲裁庭一共三次，其实不是很费精力。

开庭过程大概没啥好讲的，我提出证据，公司反驳一些（连个法务都没有的辣鸡公司，还是让人事来的），仲裁庭还是很倾向劳动者的，只是调解员和稀泥一下，各退一步，我的工资是试用期8k，我
提出了补发工资和补偿半个月的赔偿金4k，最后调解结果为赔偿3k，我在五天后收到了这笔赔偿金。

我虽然不像很多大佬一样工资非常高，我只是16年大专毕业，来北京做了一个可能入门容易的功能测试（至今还不会性能测试。。），我的基础也不好，能力也不高，但是我有一个90后火热的心，我可以对这些无良公司说不，虽然我付出了一些代价（知道19年四月份我还没找到稳定的工作，今年经济也不太好，面试机会也不多），但是我就是要为自己争一把，如果大家都忍气吞声，都不反抗这些公司，那么我们以后就被永远剥削下去么？说句很难听的话，我们程序员的反抗意识，比当代的农名工差远了，我们不能做软弱的人，只有打的一拳开，才能免得百拳来。

我现在还在苦逼的面试，哈哈，今年对于我这种普通小测试来说好难啊，还是没找到工作，个人终究对抗不了这现实

**Comment by ztc325** [comment]
![图片](https://user-images.githubusercontent.com/13145423/56175639-a4b92200-602a-11e9-9912-6141b6b180cf.png)

**Comment by ztc325** [comment]
这是当时准备的证据
![图片](https://user-images.githubusercontent.com/13145423/56175829-7d168980-602b-11e9-9afe-8eb70be2bc61.png)
纸质合同和录音

**Comment by CPdogson** [comment]
非常感谢您愿意提供这样优秀的案例，如果您愿意的话，希望您可以建立一个文件夹'Case'，然后建立子文件夹"Zhou mou"上传您的
1、自述经过和流程
2、抹去个人信息的证据范例
3、抹去个人信息的文书（如仲裁申请书等）
4、求助并留下联系方式
如果您不会操作，可以把以上资料传送至我的邮箱 CPdogson@protonmail.com
