### ISSUE TITLE
@CPdogson ,这个也是你维护呀，"劳动仲裁攻略"，计划明天公众号向大家传播下，是否可以？

### ISSUE THREAD

**Issue by githubmll** [CPdogson/996.law#19]
@CPdogson ,这个也是你维护呀，辛苦辛苦，劳动仲裁攻略，计划明天公众号向大家传播下，是否可以？

**Comment by CPdogson** [comment]
可以的，你愿意传播的话我很乐意，标注一下原地址就可以

但本周末可能会增加一些修改，包括增加法律分析等，如果使用微信公众号的话可能需要分三篇传播，建议先传播取证方面

**Comment by githubmll** [comment]
> 可以的，你愿意传播的话我很乐意，标注一下原地址就可以
> 
> 但本周末可能会增加一些修改，包括增加法律分析等，如果使用微信公众号的话可能需要分三篇传播，建议先传播取证方面

OK，按你的想法分三篇传播。

**Comment by githubmll** [comment]
@CPdogson 想了下，等你修改完后，我在进行转发传播，省的到时候出现错误
