### ISSUE TITLE
当事人资料应打码处理

### ISSUE THREAD

**Issue by GalvinGao** [CPdogson/996.law#27]
个人建议在 [README.md](https://github.com/CPdogson/996.law/blob/master/README.md#%E6%A1%88%E4%BE%8B) 中「（三）诉讼程序 - 案例」的当事人的邮箱也应进行混淆处理，以对当事人进行必要的保护
可以考虑直接去除当事人邮箱，仅保留当事人的姓即可

**Comment by CPdogson** [comment]
谢谢关心

哈哈，那个当事人当时自己要求公开邮箱，以寻求另一份工作，我想他现在也应该找到了，是时候删去了
